<?php
/**
 * DocumentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  dev.docstore.documentation
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * perf::act Documentation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: documentation@perf-act.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace dev.docstore.documentation;

use PHPUnit\Framework\TestCase;

/**
 * DocumentTest Class Doc Comment
 *
 * @category    Class
 * @description Document
 * @package     dev.docstore.documentation
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DocumentTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Document"
     */
    public function testDocument()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
    }

    /**
     * Test attribute "latest_change"
     */
    public function testPropertyLatestChange()
    {
    }

    /**
     * Test attribute "latest_update"
     */
    public function testPropertyLatestUpdate()
    {
    }

    /**
     * Test attribute "space"
     */
    public function testPropertySpace()
    {
    }

    /**
     * Test attribute "environment"
     */
    public function testPropertyEnvironment()
    {
    }

    /**
     * Test attribute "other_environments"
     */
    public function testPropertyOtherEnvironments()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }
}
