<?php
/**
 * ErrorItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  dev.docstore.documentation
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * perf::act Documentation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: documentation@perf-act.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace dev.docstore.documentation;

use PHPUnit\Framework\TestCase;

/**
 * ErrorItemTest Class Doc Comment
 *
 * @category    Class
 * @description definition of error item
 * @package     dev.docstore.documentation
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ErrorItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ErrorItem"
     */
    public function testErrorItem()
    {
    }

    /**
     * Test attribute "field"
     */
    public function testPropertyField()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }
}
