<?php
/**
 * DocumentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  dev.docstore.documentation
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * perf::act Documentation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: documentation@perf-act.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace dev.docstore.documentation;

use \dev.docstore.documentation\Configuration;
use \dev.docstore.documentation\ApiException;
use \dev.docstore.documentation\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DocumentApiTest Class Doc Comment
 *
 * @category Class
 * @package  dev.docstore.documentation
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocumentApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addNewDocument
     *
     * adds a new document.
     *
     */
    public function testAddNewDocument()
    {
    }

    /**
     * Test case for addNewDocumentForTemplate
     *
     * adds a new document by template.
     *
     */
    public function testAddNewDocumentForTemplate()
    {
    }

    /**
     * Test case for getDocument
     *
     * get latest updated documents.
     *
     */
    public function testGetDocument()
    {
    }

    /**
     * Test case for getLatestDocuments
     *
     * get latest updated documents.
     *
     */
    public function testGetLatestDocuments()
    {
    }

    /**
     * Test case for searchDocuments
     *
     * search for documents.
     *
     */
    public function testSearchDocuments()
    {
    }
}
